name: cache repo-report openssf score daily

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - 'test-actions'

jobs:
  openssf:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup code
        run: >-
          npm install
      - uses: Riyabelle25/repo-report-cache@main 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}         
        