name: cache repo-report openssf score daily

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - 'actions'

jobs:
  openssf:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}